### ISSUE TITLE
Migration problem after rebuilding docker image

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#211]
Running `docker-compose build` followed by `docker-compose up migrate` aborts with the following. Annoyingly this fails to identify which migration is causing the problem.

```
migrate_1    | Running migrations:
migrate_1    |   Applying authmultitoken.0001_initial... OK
migrate_1    |   Applying smartpanel.0006_auto_20180609_2159... OK
migrate_1    |   Applying smartpanel.0007_auto_20180609_2217... OK
migrate_1    |   Applying transport.0031_auto_20180609_1655... OK
migrate_1    |   Applying transport.0032_auto_20180610_1935... OK
migrate_1    |   Applying transport.0033_fix_route_index... OK
migrate_1    | Traceback (most recent call last):
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
migrate_1    |     return self.cursor.execute(sql, params)
migrate_1    | psycopg2.ProgrammingError: column forum_permission_forumpermission.name does not exist
migrate_1    | LINE 1: ...", "forum_permission_forumpermission"."codename", "forum_per...
migrate_1    |
migrate_1    |
migrate_1    |
migrate_1    | The above exception was the direct cause of the following exception:
migrate_1    |
migrate_1    | Traceback (most recent call last):
migrate_1    |   File "/usr/src/app/manage.py", line 10, in <module>
migrate_1    |     execute_from_command_line(sys.argv)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
migrate_1    |     utility.execute()
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
migrate_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
migrate_1    |     self.execute(*args, **cmd_options)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
migrate_1    |     output = self.handle(*args, **options)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 227, in handle
migrate_1    |     self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
migrate_1    |     **kwargs
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
migrate_1    |     for receiver in self._live_receivers(sender)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
migrate_1    |     for receiver in self._live_receivers(sender)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/machina/apps/forum_permission/receivers.py", line 27, in create_global_permissions
migrate_1    |     create_permissions()
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/machina/apps/forum_permission/receivers.py", line 18, in create_permissions
migrate_1    |     gp = ForumPermission.objects.get(codename=config['fields']['codename'])
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
migrate_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
migrate_1    |     num = len(clone)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
migrate_1    |     self._fetch_all()
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
migrate_1    |     self._result_cache = list(self._iterable_class(self))
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
migrate_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
migrate_1    |     raise original_exception
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
migrate_1    |     cursor.execute(sql, params)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
migrate_1    |     return super(CursorDebugWrapper, self).execute(sql, params)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
migrate_1    |     return self.cursor.execute(sql, params)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
migrate_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
migrate_1    |     raise value.with_traceback(tb)
migrate_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
migrate_1    |     return self.cursor.execute(sql, params)
migrate_1    | django.db.utils.ProgrammingError: column forum_permission_forumpermission.name does not exist
migrate_1    | LINE 1: ...", "forum_permission_forumpermission"."codename", "forum_per...
migrate_1    |                                                              ^
migrate_1    |
tfc_web_migrate_1 exited with code 1                                                              ^
```

**Comment by jw35** [comment]
Hm, rebuilding again today (and using `docker-compose build --no-cache`) and the problem no longer manifests. Closing, while puzeled...
