### ISSUE TITLE
station_board throws 500 Internal Srever Error overnight

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#88]
```
2018-04-05 23:55:09,691 INFO Cache miss for station_board!CBG 0
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Header><ns0:AccessToken xmlns:ns0="http://thalesgroup.com/RTTI/2013-11-28/Token/types"><ns0:TokenValue>d566da96-5384-4832-9349-730300ec63e4</ns0:TokenValue></ns0:AccessToken></soap-env:Header><soap-env:Body><ns0:GetDepartureBoardRequest xmlns:ns0="http://thalesgroup.com/RTTI/2017-10-01/ldb/"><ns0:numRows>50</ns0:numRows><ns0:crs>CBG</ns0:crs><ns0:timeOffset>0</ns0:timeOffset></ns0:GetDepartureBoardRequest></soap-env:Body></soap-env:Envelope>
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetDepartureBoardResponse xmlns="http://thalesgroup.com/RTTI/2017-10-01/ldb/"><GetStationBoardResult xmlns:lt="http://thalesgroup.com/RTTI/2012-01-13/ldb/types" xmlns:lt6="http://thalesgroup.com/RTTI/2017-02-02/ldb/types" xmlns:lt7="http://thalesgroup.com/RTTI/2017-10-01/ldb/types" xmlns:lt4="http://thalesgroup.com/RTTI/2015-11-27/ldb/types" xmlns:lt5="http://thalesgroup.com/RTTI/2016-02-16/ldb/types" xmlns:lt2="http://thalesgroup.com/RTTI/2014-02-20/ldb/types" xmlns:lt3="http://thalesgroup.com/RTTI/2015-05-14/ldb/types"><lt4:generatedAt>2018-04-05T23:55:10.1305913+01:00</lt4:generatedAt><lt4:locationName>Cambridge</lt4:locationName><lt4:crs>CBG</lt4:crs><lt4:platformAvailable>true</lt4:platformAvailable><lt7:busServices><lt7:service><lt4:std>00:15</lt4:std><lt4:etd>On time</lt4:etd><lt4:platform>BUS</lt4:platform><lt4:operator>Great Northern</lt4:operator><lt4:operatorCode>GN</lt4:operatorCode><lt4:serviceType>bus</lt4:serviceType><lt4:serviceID>GDQukuAvZdWgriLiI6FJhA==</lt4:serviceID><lt5:origin><lt4:location><lt4:locationName>Cambridge</lt4:locationName><lt4:crs>CBG</lt4:crs></lt4:location></lt5:origin><lt5:destination><lt4:location><lt4:locationName>Kings Lynn</lt4:locationName><lt4:crs>KLN</lt4:crs></lt4:location></lt5:destination></lt7:service></lt7:busServices></GetStationBoardResult></GetDepartureBoardResponse></soap:Body></soap:Envelope>
Internal Server Error: /smartpanel/station_board
Traceback (most recent call last):
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfc_prod/tfc_web/tfc_web/smartpanel/views/widgets/station_board.py", line 54, in station_board
    for service in raw_data['trainServices']['service']:
TypeError: 'NoneType' object is not subscriptable
2018-04-05 23:55:10,151 ERROR Internal Server Error: /smartpanel/station_board
Traceback (most recent call last):
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tfc_prod/tfc_web/tfc_web/smartpanel/views/widgets/station_board.py", line 54, in station_board
    for service in raw_data['trainServices']['service']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jw35** [comment]
Should be fixed in 6e8dde6
